### ISSUE TITLE
Missing RSS feed

### ISSUE THREAD

**Issue by otopetrik** [KMahoney/kmahoney.github.io#3]
There is no RSS (or Atom) feed.
Without it, it is impossible to add [articles](http://kevinmahoney.co.uk/articles/) page to feedly.com.
That makes is very easy to miss future articles.

**Comment by KMahoney** [comment]
Let me know if http://kevinmahoney.co.uk/feed.xml works for you.

**Comment by otopetrik** [comment]
The linked feed works, thanks!

Note that as-is, it is practically impossible to discover.
The URL to xml *itself* has to be added to feedly (and is linked only from this list of issues).
Please consider adding _link rel=alternate_.

See:
https://developer.mozilla.org/en-US/docs/Archive/RSS/Getting_Started/Syndicating#Adding_the_.3Clink.3E
or
https://stackoverflow.com/questions/19345075/how-does-a-service-like-feedly-obtain-the-rss-feeds-from-a-website-when-the-webs/19351293#19351293

With such _link rel=alternate_ tag, it is as easy as copy-pasting URL of an interesting article, and feedly (and others rss readers) figure out the proper feed URL from the link tag.

**Comment by KMahoney** [comment]
I don't have anything handy to test it with, but I've added the `link`

**Comment by otopetrik** [comment]
Tested with feedly.com, now it works with just copy-pasting article URL. Thanks!
